import { PlanType, PlanData } from "./constants";

export const plans: Record<PlanType, PlanData> = {
    freemium: {
        name: "Freemium",
        price: "$0/Month",
        features: {
            projects: "1 Active at any time\n3 Projects archived",
            contacts: true,
            calendar: true,
            media: true,
            email: true,
            collaborators: "1 Person",
            chat: "1 Person",
            storage: "200 Megabytes",
            archive: "1 Year",
            receipts: "none",
            timesheets: "none",
            support: "Email",
        },
    },
    silver: {
        name: "Silver",
        price: "$2/Month",
        nextBillingDate: "14 December 2025",
        renewalStatus: true,
        features: {
            projects: "2 Active at any time\n\n10 Projects archived",
            contacts: true,
            calendar: true,
            media: true,
            email: true,
            collaborators: "5 People",
            chat: "5 People",
            storage: "1 gigabytes",
            archive: "2 Years",
            receipts: "none",
            timesheets: "none",
            support: "Email & Phone",
            costLabel: "Launching in Q2, 2025",
        },
    },
    platinum: {
        name: "Platinum",
        price: "$2/Month",
        nextBillingDate: "14 December 2025",
        renewalStatus: true,
        features: {
            projects: "Unlimited",
            contacts: true,
            calendar: true,
            media: true,
            email: true,
            collaborators: "Unlimited",
            chat: "Unlimited",
            storage: "1 terabytes",
            archive: "Unlimited",
            receipts: "none",
            timesheets: "none",
            support: "Email & Phone",
            costLabel: "Launching in Q2, 2025",
        },
    },
};
